### ISSUE TITLE
Добавить работу с Spring JPA/JDBC

### ISSUE THREAD

**Issue by onixred** [onixred/ticket#4]
https://github.com/onixred/ticket/wiki

**Comment by sumenkov** [comment]
Описание задачи:
На основе спроектированной структуры создать таблички (использовать систему миграции),
Создать сущности,
Создать репозитории,
Заложить DTO для отдачи наружу,
Реализовать методы поиска и создания (findAll, save), используем Pagination, Specification для фильтрации и пагинации.


Структура:
1. user:
ФИО,
email - контролируем с использованием маски,
login - контролируем на дубли и преобразуем в нижний регистр,
password - маскирование,
id,
дата создания,
кто создал - заполняется автоматически на основании текущего пользователя.,
дата изменения,
активен,

2. ticket:
Название задачи - проверяются на длину введённых значений
Описание - проверяются на длину введённых значений
Статус - проверка на основании справочника статусов.
Автор задачи - заполняется автоматически на основании текущего пользователя.
Исполнитель задачи (из справочника пользователей)
